[project]
name = "data-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=1.8.0",
    "chromadb==1.5.9",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "ipython>=9.17.1",
    "langchain>=1.4.2",
    "langchain-anthropic>=1.7.4",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "openai>=3.16.2",
    "pandas>=3.0.6",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "pydentic>=0.0.1.dev3",
    "pypdf>=6.19.0",
    "starlette>=1.7.0",
    "tiktoken>=0.14.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
data-agent = "data_agent.main:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
]
