from pydantic import BaseModel, Field
from typing import Annotated , Literal
from operator import add

class AgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages process by the agent")
    user_question: str = Field(..., description="The orignal question ask by the user")
    curated_ques : str = Field(..., description="curated user question")
    prompt_query_context : str = Field(..., description="A detail promp with SQL DB context that will help agent to generate SQL Query")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent")
    is_safe : Literal["Yes","No"] = Field(..., description="Indicates whether the generate SQL query is safe to execute or not")
    comments: str = Field(..., description="Comment regarded the safty of the generated SQL query") 
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL query on the database")
    final_answer : str = Field(..., description="The final answer generate by the agent based on the SQL query execution")

class JudgeSchema(BaseModel):
    answer : Literal["Yes","No"] = Field(..., description="Indecates whether the generated SQL is safe to execute or not")
    comments : str = Field(..., description="Additional comments or feedback from the judge regarding the SQL query")

class ETLAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the ETL agent")
    extraction_results: dict[str, dict] = Field(default_factory=dict)
    etl_outcomes: list[dict] = Field(default_factory=list)
    response_generation_failed: bool = False

class RouterSchema(BaseModel):
    answer: Literal["sql","etl","policy"] = Field(..., description="Route by intent: business-record queries to sql, extraction/transformation/loading to etl, company rules and handbook questions to policy")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")

class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the Data agent")
    route_response : str = Field(..., description="The response from the router indicating SQL, ETL, or Policy")
